channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - cudatoolkit
  - numpy=1.26.2
  - pytorch=2.1.1
  - scikit-learn=1.3.0
  - loguru=0.5.3
  - botorch=0.9.5
  - gpytorch=1.11
  - pandas=2.1.4
  - scipy=1.11.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - ipython=8.19.0
  - pre-commit=3.6.0
  - mypy=1.8.0
  - pytest=7.4.4
  - lightning=2.0.3
